config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :populars do
    collection do
      get 'detail_artist'
    end
  end

  root 'populars#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/populars_controller.rb
class PopularsController < ApplicationController

  require 'rest-client'

  def index
    keyword = params['keyword'].present? ? params['keyword'].gsub(/\s+/, '+') : 'Indonesia'
    @keyword = params['keyword'].present? ? params['keyword'].gsub(/\s+/, '+') : nil
    @page = params['page'].present? ? params['page'].to_i : 1

    # Get result from API last.fm
    results = JSON.parse(RestClient.get("http://ws.audioscrobbler.com/2.0/?method=geo.gettopartists&country=#{keyword}&api_key=385abba2af409c4db2a8829bcaec948a&limit=5&page=#{@page}&format=json"))
    if results["error"].present?
      flash[:alert] = "country name invalid or not listed"
      redirect_to root_path
    else
      @top_artist = results["topartists"]["artist"]
      @values = WillPaginate::Collection.create(@page, 5,  results["topartists"]["@attr"]["totalPages"]) do |pager|
        pager.replace @top_artist
      end
    end
  end

  def detail_artist
    @name = params["name"]
    # Get result from API last.fm
    results = JSON.parse(RestClient.get("http://ws.audioscrobbler.com/2.0/?method=artist.gettoptracks&artist=#{@name}&api_key=385abba2af409c4db2a8829bcaec948a&format=json"))
    @top_tracks = results["toptracks"]["track"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/populars_helper.rb
module PopularsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestDay</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/populars/detail_artist.html.erb
<div class="container">
  <div class="popular">
    <h2 class="title">TOP TRACKS OF <%=@name%></h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Title</th>
          <th>URL</th>
        </tr>
      </thead>
      <tbody>
        <% @top_tracks.each do |track|%>
          <tr>
            <td><%=track["name"]%></td>
            <td><%=link_to track["url"], track["url"]%></td>
          </tr>
        <%end%>
      </tbody>

    </table>
  </div>
</div>

app/views/populars/index.html.erb
<div class="container">
  <div class="popular">
    <div class="col-md-12">
      <div class="row ">
        <div class="col-md-6 align-self-center"> <h2 class="title">THE MOST POPULAR</h2> </div>
      </div>
      <% flash.each do |key, value| %>
        <div class="alert alert-danger" role="alert">
          <%= content_tag :div, value, class: "flash #{key}" %>
        </div>
      <% end %>
      <%= form_tag(root_path, method: :get) do %>

        <div class="col-md-8">

          <div class="row">
            <div class="col-md-7">
              <%=text_field_tag 'keyword', @keyword, placeholder:'Enter Country Name', class: "form-control mb-2 mb-sm-0"%>
            </div>
            <div class="col-md-1"><%= submit_tag 'Search',class: "btn btn-primary" %></div>
          </div>
        </div>
      <% end %>
    </div>
    &nbsp;
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Band Name</th>
          <th>Picture</th>
        </tr>
      </thead>
      <tbody>
        <% @top_artist.each do |artist|%>
          <tr>
            <td>
              <%= link_to detail_artist_populars_path(name: artist["name"]), target: :_blank do %>
                <%=artist["name"]%>
              <%end%>
            </td>
            <td>
              <%= link_to detail_artist_populars_path(name: artist["name"]), target: :_blank do %>
                <%=image_tag artist["image"][1]["#text"]%>
              <%end%>

            </td>
          </tr>
        <%end%>
      </tbody>

    </table>

    <%= will_paginate @values, params: { keyword: @keyword }, renderer: BootstrapPagination::Rails %>
  </div>
</div>